[book]
authors = ["Joao Vitor Maia"]
language = "en"
multilingual = false
src = "src"
title = "Mart: Math as art"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
mathjax-support = true